// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATuXn92fOQWT5D8OCgBma1d_0yU8auM2U',
    appId: '1:914608974935:web:234aa120c712c7418a8712',
    messagingSenderId: '914608974935',
    projectId: 'kalam-dream-labs',
    authDomain: 'kalam-dream-labs.firebaseapp.com',
    storageBucket: 'kalam-dream-labs.firebasestorage.app',
    measurementId: 'G-JNB9BS194P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31I8WWya35nXKp0PPuWVjE8Bu1YCq2K8',
    appId: '1:914608974935:android:5ac8cd29f2c71f668a8712',
    messagingSenderId: '914608974935',
    projectId: 'kalam-dream-labs',
    storageBucket: 'kalam-dream-labs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxo0DF8yYsHjuYZcuLmfNn2OrWCft90-o',
    appId: '1:914608974935:ios:9aab7dd6bbfe8aab8a8712',
    messagingSenderId: '914608974935',
    projectId: 'kalam-dream-labs',
    storageBucket: 'kalam-dream-labs.firebasestorage.app',
    iosBundleId: 'com.example.kdlAttendanceApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxo0DF8yYsHjuYZcuLmfNn2OrWCft90-o',
    appId: '1:914608974935:ios:5c62c4f3ae1139418a8712',
    messagingSenderId: '914608974935',
    projectId: 'kalam-dream-labs',
    storageBucket: 'kalam-dream-labs.firebasestorage.app',
    iosBundleId: 'com.example.kdlAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATuXn92fOQWT5D8OCgBma1d_0yU8auM2U',
    appId: '1:914608974935:web:90a8bd933b55ada68a8712',
    messagingSenderId: '914608974935',
    projectId: 'kalam-dream-labs',
    authDomain: 'kalam-dream-labs.firebaseapp.com',
    storageBucket: 'kalam-dream-labs.firebasestorage.app',
    measurementId: 'G-QSPJKWYX56',
  );
}
